#!/usr/bin/env ruby
# encoding: utf-8

=begin
Copyright Daniel Meißner <dm@3st.be>, 2012

This file is part of filestatus to send xmpp notifications if
critical system files are modified.

This script is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This Script is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with filestatus. If not, see <http://www.gnu.org/licenses/>.
=end

require "rubygems"
require "bundler"

require 'pathname'
require 'rainbow'

# declarations
PWD_BIN      = Pathname.pwd + 'filestatus.rb'
PWD_INIT     = Pathname.pwd + 'init.rb'

INSTALL_PATH = Pathname('/usr/local/sbin')
BIN          = INSTALL_PATH + 'filestatus'

INIT_PATH    = Pathname('/etc/init.d/')
INIT_BIN     = INIT_PATH + 'filestatus'

# tasks

desc 'Install filestatus'
task :install do
  if File.symlink(PWD_BIN, BIN)
    puts "Symlink #{PWD_BIN} -> #{BIN} created".color(:green)

    File.chmod(0700, PWD_BIN)
  else
    puts "Symlink creation failed.".color(:red)
  end

  if File.symlink(PWD_INIT, INIT_BIN)
    puts "Symlink #{PWD_INIT} -> #{INIT_BIN} created".color(:green)

    File.chmod(0700, PWD_INIT)

    %x{cd /etc/init.d/; update-rc.d filestatus defaults}
  else
    puts "Symlink creation #{PWD_INIT} -> #{INIT_BIN} failed.".color(:red)
  end

  puts "Configure filestatus in #{BIN}".color(:green)
  puts "Start filestatus daemon /etc/init.d/filestatus start".color(:blue)

end

desc 'Uninstall filestatus'
task :uninstall do
  if File.exist?(BIN)
    File.delete(BIN)
    puts "#{BIN} deleted".color(:green)
  else
    puts "#{BIN} not installed".color(:yellow)
  end

  if File.exist?(INIT_BIN)
    %x{cd /etc/init.d/; update-rc.d filestatus disable}
    File.delete(INIT_BIN)
    puts "#{INIT_BIN} deleted".color(:green)
  else
    puts "#{INIT_BIN} not installed".color(:yellow)
  end

end

desc 'Install all filestatus dependencies'
task :bundle do
  Bundler.setup
end